export const DELETE_PROGRESS_UPDATE_OPTION = "DELETE_PROGRESS_UPDATE_OPTION";
export const UPDATE_PROGRESS_UPDATE_OPTION = "UPDATE_PROGRESS_UPDATE_OPTION";
export const CREATE_PROGRESS_UPDATE_OPTION = "CREATE_PROGRESS_UPDATE_OPTION";

export const UPDATE_PROJECT_OPTION = "UPDATE_PROJECT_OPTION";
export const DELETE_PROJECT_OPTION = "DELETE_PROJECT_OPTION";
