export const PROJECT_SELECTED = 'PROJECT_SELECTED';
export const PATCH_PROJECTS_NAME = 'PATCH_PROJECTS_NAME';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const CREATE_PROJECT = 'CREATE_PROJECT';


export const DELETE_PROGRESS_UPDATE = 'DELETE_PROGRESS_UPDATE';
export const UPDATE_PROGRESS_UPDATE = 'UPDATE_PROGRESS_UPDATE';
export const CREATE_PROGRESS_UPDATE = 'CREATE_PROGRESS_UPDATE';
export const DELETE_PROJECT_DELETE_PROGRESS_UPDATES = 'DELETE_PROJECT_DELETE_PROGRESS_UPDATES';
